accounts/urls.py
from django.conf.urls import include, url

from accounts.views import (
    CustomUserCreateView,
    CustomUserLoginView,
    LogoutView,
    UserConnectionsView
    )


urlpatterns = [
    url(r'^register/', CustomUserCreateView.as_view(), name='register'),
    url(r'^login/', CustomUserLoginView.as_view(), name='login'),
    url(r'^connections/', UserConnectionsView.as_view(), name='settings'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    ]

qscore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', login_required(
        TemplateView.as_view(template_name='analytics/00_dashboard.html')), name='analytics'),
    # url(r'^programs/$', TemplateView.as_view(template_name='programs.html'), name='programs'),
]

rl_proto2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required


from integrations.salesforce.settings import (
    SALESFORCE_PROD_AUTH_URL,
    SALESFORCE_SANDBOX_AUTH_URL
    )


urlpatterns = [
    url(r'^', include('program_manager.urls'), name='programs'),
    url(r'^analytics/', include('qscore.urls'), name='analytics'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^reports/', include('reports.urls'), name='reports'),
    url(r'^welcome/$', login_required(TemplateView.as_view(template_name='welcome.html')), name='welcome'),

    # Incoming Oauth Redirects
    url(r'^oauth/', include('integrations.oauth'), name='oauth'),

    # Outgoing Oauth Redirects
    url(
        r'^salesforce_auth/$',
        RedirectView.as_view(url=SALESFORCE_PROD_AUTH_URL, permanent=False),
        name='salesforce_auth_request'
        ),
    url(
        r'^salesforce_sandbox/$',
        RedirectView.as_view(url=SALESFORCE_SANDBOX_AUTH_URL, permanent=False),
        name='salesforce_sandbox_auth_request'
        ),


    url(r'^admin/', include(admin.site.urls)),
]

rl_proto2/templates/base.html
{% load static %}
{% load staticfiles %}
{% load i18n %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE }}" class="no-js">
    <head>
        {% block head %}
            {% block meta %}
                <meta charset="utf-8">
                <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
                <meta property="og:title" content="RingLead Prototype v2" />
                <meta property="og:url" content="http://www.ringlead.com"/>
                <meta property="og:description" content="RingLead Prototype"/>
            {% endblock %}
                <title>
                    {% block title %}
                        {% trans 'RingLead Prototype' %}
                    {% endblock %}
                </title>
        {% endblock %}

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" media="screen">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootswatch-paper.css' %}" media="screen">
        <link rel="stylesheet" href="{% static 'bootstrap/css/custom.css' %}" media="screen">
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <link href="{% static 'bootstrap-toggle-master/css/bootstrap-toggle.min.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap-select-master/dist/css/bootstrap-select.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui/smoothness/jquery-ui.css' %}" />

        {% block extra_css %}{% endblock %}

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
        <script src="{% static 'js/jquery-ui.js' %}"></script>

        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'justgage/raphael.min.js' %}"></script>
        <script src="{% static 'justgage/justgage.min.js' %}"></script>
        <script src="{% static 'bootstrap-toggle-master/js/bootstrap-toggle.min.js' %}"></script>
        <script src="{% static 'bootstrap-select-master/js/bootstrap-select.js' %}"></script>
        {% block extra_js %}{% endblock %}
        <!-- Enable custom bootstrap-select lib -->

    </head>
    <body>

        {% block body %}

            {% include 'nav.html' %}
              <div class="col-md-12">
                {% block layout %}
                {% endblock %}
              </div>
            </div>
        {% endblock %}  <!-- / body block -->

        <!-- <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script> -->
        <!-- <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap-switch.js' %}"></script> -->
    </body>

    <script type='text/javascript'>
      function enable_selectpickers() {
        $('select.selectpicker').selectpicker();
        $('select.selectpicker').selectpicker('setStyle', 'selectpicker-flat');
        $('.bootstrap-select').removeClass('form-control');
        $('.bootstrap-select').addClass('selectpicker-container');
      }
      $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        enable_selectpickers();
      });
    </script>
</html>

rl_proto2/templates/connections.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Continue Setup" %}{% endblock %}

{% block layout %}
    {% block content %}

    <div id="loginwrap">
      <div class="container">
        <div class="row" align="center">
              {% include 'includes/messages.html' %}
              <br>
              <div class="col-md-6 col-md-offset-3 well" style="height:350px">
                  <div align="center">
                      <h2>Connections</h2>
                      <p>Connect your CRM and marketing databases</p>
                      <br>
                      <!-- BEGIN Salesforce Connection -->
                      {% if salesforce_accounts %}
                          {% for account in salesforce_accounts %}
                              {% if account.active %}
                              <button type="button" class="btn btn-lg btn-success btn-block" data-toggle="modal" data-target="#SalesforceSettingsModal">Salesforce is Connected <i class="fa fa-inverse fa-check-circle"></i></button>
                              {% else %}
                              <button type="button" class="btn btn-lg btn-warning btn-block" data-toggle="modal" data-target="#SalesforceTypeSelectModal">Reconnect Salesforce <i class="fa fa-inverse fa-cloud"></i></button>
                              {% endif %}
                          {% endfor %}
                      {% else %}
                      <button type="button" class="btn btn-lg btn-warning btn-block" data-toggle="modal" data-target="#SalesforceTypeSelectModal">Connect Salesforce <i class="fa fa-inverse fa-cloud"></i></button>
                      {% endif %}
                      <!-- END Salesforce Connection -->
                      <a href="#" class="btn btn-lg btn-warning btn-block" disabled>Connect Marketo <i class="fa fa-inverse fa-cloud"></i></a>
                      <a href="#" class="btn btn-lg btn-warning btn-block" disabled>Connect Pardot <i class="fa fa-inverse fa-cloud"></i></a>
                  </div>
              </div>
        </div>
        <div class="row">
            <div align="center" class="col-md-6 col-md-offset-3">
                {% if salesforce_accounts %}
                    <a href="{% url 'select_program_type' %}" class="btn btn-lg btn-warning">Get Started Optimizing Your Data!</a>
                {% endif %}
            </div>
        </div>

      </div>
    </div>




    <!-- Salesforce Production Vs. Sandbox Selection Modal -->
    <div class="modal fade" id="SalesforceTypeSelectModal" tabindex="-1" role="dialog" aria-labelledby="SalesforceTypeSelectModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="SalesforceTypeSelectModalLabel">Select Salesforce Type</h4>
          </div>
          <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'salesforce_sandbox_auth_request' %}" class="btn btn-lg btn-warning btn-block">Connect a Sandbox Account</a>
                </div>
                <div class="col-md-6">
                  <a href="{% url 'salesforce_auth_request' %}" class="btn btn-lg btn-warning btn-block">Connect a Production Account</a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Salesforce Settings Modal -->
    <div class="modal fade" id="SalesforceSettingsModal" tabindex="-1" role="dialog" aria-labelledby="SalesforceSettingsModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Salesforce Connection Settings</h4>
          </div>
          <div class="modal-body">
            {% if salesforce_accounts %}
                {% for account in salesforce_accounts %}
                    {% if account.active %}
                        <table class="table well">
                            <tbody>
                                <tr>
                                    <td>Salesforce Instance URL</td>
                                    <td>{{ account.instance_url }}</td>
                                </tr>
                                <tr>
                                    <td>Salesforce Org Id</td>
                                    <td>{{ account.salesforce_organization_id }}</td>
                                </tr>
                                <tr>
                                    <td>Salesforce User Id</td>
                                    <td>{{ account.salesforce_user_id }}</td>
                                </tr>
                            </tbody>
                        </table>
                        {{ account.}}
                    {% else %}
                    {% endif %}
                {% endfor %}
            {% else %}
            <a href="{% url 'salesforce_auth_request' %}" class="btn btn-lg btn-warning btn-block">Connect Salesforce</a>
            {% endif %}
            <div class="modal-footer">
                <button type="button" class="btn btn-danger disabled">Delete Connection</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endblock %}
{% endblock %}

{% comment %}
**registration/registration_complete.html**

Used after successful completion of the registration form. This
template has no context variables of its own, and should simply inform
the user that an email containing account-activation information has
been sent.
{% endcomment %}

rl_proto2/templates/index.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}

<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
      <h3>Welcome {{ user.first_name }}</h3>
      <p>Where should we get started today?</p>
  </div>
</div>

<!-- row -->
<div class="row">
  <div class="col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2 col-xs-5 col-xs-offset-1" style="margin-top:20px;">
      <a href="{% url 'programs' %}" class="btn btn-large btn-primary btn-block">
          <i class="fa fa-dashboard fa-5x"></i><br>
          <span class="cta-primary-btn-text">Program Dashboard</span>
      </a>
  </div>
  <div class="col-md-3 col-sm-4 col-xs-5" style="margin-top:20px;">
      <a href="{% url 'reports' %}" class="btn btn-large btn-warning btn-block">
          <i class="fa fa-bar-chart fa-5x"></i><br>
          <span class="cta-primary-btn-text">Get Started</span>
      </a>
  </div>
</div>
<!-- / row -->
<!-- row -->
<div class="row">
  <div class="col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2 col-xs-5 col-xs-offset-1" style="margin-top:20px;">
      <a href="{% url 'import_select' %}"  class="btn btn-large btn-primary btn-block">
          <i class="fa fa-cloud-upload fa-5x"></i><br>
          <span class="cta-primary-btn-text">Import</span>
      </a>
  </div>
  <div class="col-md-3 col-sm-4 col-xs-5" style="margin-top:20px;">
      <a href="#"  class="btn btn-large btn-primary btn-block" disabled>
          <i class="fa fa-refresh fa-5x"></i><br>
          <span class="cta-primary-btn-text">Smart Clean</span>
      </a>
  </div>
</div>
<!-- / row -->

<br>


{% endblock %}

rl_proto2/templates/nav.html
{% load static %}
{% load staticfiles %}

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">RingLead</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      {% if user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_admin %}
        <li><a href="/admin/">RingLead Admin</a></li>
        {% endif %}
        <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Settings <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">User Management</a></li>
              <li><a href="{% url 'accounts:settings' %}">Connections</a></li>
              <li><a href="#">Billing & Payments</a></li>
            </ul>
        </li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav navbar-right">
          <!-- If anonymous -->
          <li><a href="{% url 'accounts:register' %}">Sign Up</a></li>
          <li><a href="{% url 'accounts:login' %}">Log In</a></li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

rl_proto2/templates/segments-actions.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}

<div class="row">
  <div class="col-md-4 col-md-offset-1" align="left">
    <font size="6">Actions</font>
  </div>
  <div class="col-md-4" >
      <a class="btn btn-primary " href="{% url 'dashboard' %}" >Step 1</a><a class="btn btn-primary active" href="{% url 'actions' %}">Step 2</a><a class="btn btn-primary" href="#">Step 3</a>
  </div>
  <div class="col-md-4" align="right">
      <a href="#" class="btn btn-lg btn-success"><i class="fa fa-plus-circle"></i> New</a>
  </div>
</div>
<br>
<div class="row">
  <div class=" col-md-4" align="center" style="padding:5px">
    <h2>Cool ACTIONS</h2>
  </div>
  <div class="col-md-4" align="center" style="padding:5px">
      <div class=" well well-sm">
        <h4>Sales Qualified Leads</h4>
      </div>
  </div>
  <div class="col-md-4" align="center" style="padding:5px">
      <div class=" well well-sm">
        <h4>Webinar Leads</h4>
      </div>
  </div>
</div>

{% endblock %}

rl_proto2/templates/welcome.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}


	<div id="headerwrap">
		<div class="container">
			<br>
			<div class="row">
				<div class="col-md-12 fade-in welcome_0" align="center">
								<span style="font-size:36px">Welcome {{ user.first_name }}</span><br>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 fade-in welcome_1" align="center">
					<span style="font-size:20px">See how RingLead can help you...</span>
				</div>
			</div>


			<div class="row" style="padding-top:30px">
					<div class="col-md-8 col-md-offset-2">
								<br>
								<div class="row ">
									<div class="col-sm-4 fade-in welcome_2">
										<div align="center">
                        <i class="fa fa-line-chart fa-5x"></i>
										</div>
										<h4 align="center">Make Marketing Better</h4>
										<p>Improve your marketing metrics by providing smart data operations in Salesforce, Marketo and more.</p>
									</div><!--/col-lg-4 -->
									<div class="col-sm-4 fade-in welcome_3">
                    <div align="center">
                      <i class="fa fa-usd fa-5x"></i>
										</div>
										<h4 align="center">Better Equip Your Sales Team</h4>
										<p>Make sales reps drastically more effective by letting them focus on closing instead of data wrangling.</p>
									</div><!--/col-lg-4 -->

									<div class="col-sm-4 fade-in welcome_4">
										<div align="center">
                      <i class="fa fa-dashboard fa-5x"></i>
										</div>
										<h4 align="center">Get True Data Visibility</h4>
										<p>Attain crystal clear analysis on the factors that are driving your business.</p>

									</div><!--/col-lg-4 -->
								</div><!-- /row -->
                <br>
								<div class="row">
										<div class="col-md-12 fade-in welcome_btn" align="center">
											<a href="{% url 'accounts:settings' %}" class="btn btn-lg btn-warning">Begin Setup <i class="fa fa-angle-double-right fa-inverse"></i></a>
										</div>
								</div>
					</div>

{% endblock %}