accounts/urls.py
from django.conf.urls import include, url

from accounts.views import (
    CustomUserCreateView,
    CustomUserLoginView,
    LogoutView,
    UserConnectionsView
    )


urlpatterns = [
    url(r'^register/', CustomUserCreateView.as_view(), name='register'),
    url(r'^login/', CustomUserLoginView.as_view(), name='login'),
    url(r'^connections/', UserConnectionsView.as_view(), name='settings'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    ]

program_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from program_manager import views

urlpatterns = [
    url(r'^$', views.ProgramDashboardView.as_view(), name='programs'),
    url(r'^list/$', views.ProgramListView.as_view(), name='program_list'),
    url(r'^select_program_type/$', views.ProgramSelectType.as_view(), name='select_program_type'),
    url(r'^select_program_type/(?P<pk>[0-9]+)$',views.ProgramSelectType.as_view(), name='select_program_type_pk'),
    url(r'^analysis_select/$',login_required(TemplateView.as_view(template_name='program_manager/analysis_select.html')),name='analysis_select'),
    url(r'^analysis_confirm/$',login_required(TemplateView.as_view(template_name='program_manager/analysis_confirm.html')),name='analysis_confirm'),
    url(r'^batch_select/(?P<pk>[0-9]+)$',views.ProgramAddFiltersView.as_view(),name='batch_select'),
    url(r'^select_actions/(?P<pk>[0-9]+)$',views.ProgramSelectActionsView.as_view(),name='select_actions'),
    url(r'^batch_confirm/(?P<pk>[0-9]+)$',views.ProgramSetNameView.as_view(),name='batch_confirm'),
    url(r'^fieldfilter/(?P<pk>[0-9]+)/delete',views.DeleteFieldFilterView.as_view(),name='delete_fieldfilter'),
    url(r'^import_select/$',views.CreateListImportProgramView.as_view(),name='import_select'),
    url(r'^import_program/(?P<pk>[0-9]+)/$', views.ListImportProgramView.as_view(), name='import_program_details'),
    url(r'^(?P<pk>[0-9]+)/archive$', views.archive_program, name='archive_program'),
    url(r'^qs_data/(?P<pk>[0-9]+)/$', views.qs_data, name='qs_data'),
    url(r'^debug_dedupe/(?P<pk>[-\w]+)$', views.debug_dedupe, name='debug_dedupe'),
    url(r'^debug_apply_dedupe/(?P<pk>[-\w]+)/(?P<id>[-\w]+)$', views.debug_apply_dedupe, name='debug_apply_dedupe'),
]

qscore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', login_required(
        TemplateView.as_view(template_name='analytics/00_dashboard.html')), name='analytics'),
    # url(r'^programs/$', TemplateView.as_view(template_name='programs.html'), name='programs'),
]

rl_proto2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required


from integrations.salesforce.settings import (
    SALESFORCE_PROD_AUTH_URL,
    SALESFORCE_SANDBOX_AUTH_URL
    )


urlpatterns = [
    url(r'^', include('program_manager.urls'), name='programs'),
    url(r'^analytics/', include('qscore.urls'), name='analytics'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^reports/', include('reports.urls'), name='reports'),
    url(r'^welcome/$', login_required(TemplateView.as_view(template_name='welcome.html')), name='welcome'),

    # Incoming Oauth Redirects
    url(r'^oauth/', include('integrations.oauth'), name='oauth'),

    # Outgoing Oauth Redirects
    url(
        r'^salesforce_auth/$',
        RedirectView.as_view(url=SALESFORCE_PROD_AUTH_URL, permanent=False),
        name='salesforce_auth_request'
        ),
    url(
        r'^salesforce_sandbox/$',
        RedirectView.as_view(url=SALESFORCE_SANDBOX_AUTH_URL, permanent=False),
        name='salesforce_sandbox_auth_request'
        ),


    url(r'^admin/', include(admin.site.urls)),
]

program_manager/models.py
from django.core.urlresolvers import reverse
from django.db import models
from polymorphic import PolymorphicModel

from accounts.models import CustomUser as User
from integrations.models import ExternalTable, ExternalField
from program_manager.choices import *

class Program(PolymorphicModel):
    """A generic job that contains a connected system (e.g. Salesforce), some
    defined actions and some granular settings."""

    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    last_run = models.DateTimeField(null=True, blank=True)
    name = models.CharField(max_length=256, null=True, blank=True)
    status = models.CharField(max_length=256, choices=STATUSES, default='CREA')
    table_schema = models.ForeignKey(ExternalTable, null=True)
    read_only = models.BooleanField(default=False)
    dedupe = models.BooleanField(default=True)
    analyze_only = models.BooleanField(default=False)
    # # Person Info Optimization Options
    # person_name_proper_case = models.BooleanField(default=True)
    # # Company Info Optimization Options
    # address_optimize = models.BooleanField(default=True)
    # phone_optimize = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name or 'unnamed'

    @property
    def progress(self):
        qs = self.get_current_quality_score()
        return qs.progress if qs else None

    def get_current_quality_score(self):
        """Returns the most recently calculated Quality Score"""
        qs = self.get_all_quality_scores()
        return qs[0] if qs else None

    def get_all_quality_scores(self):
        """Returns the most recently calculated Quality Score"""
        return self.qualityscore_set.all().order_by('-id')

    def get_table_filters(self):
        """Returns all TableFilter objects related to Program"""
        return self.tablefilter_set.all()

    def get_field_filters(self):
        """Returns all FieldFilter objects related to Program"""
        return self.fieldfilter_set.all()

    def get_dup_match_rules(self):
        """Returns all DupMatchRule objects related to Program"""
        return self.dupmatchrule_set.all()

    def get_surviving_record_rules(self):
        """Returns all SurvivingRecordRule objects related to Program"""
        return self.survivingrecordrule_set.all()

    def get_surviving_value_rules(self):
        """Returns all SurvivingValueRule objects related to Program"""
        return self.survivingvaluerule_set.all()

    @property
    def is_running(self):
        return self.status == 'RUN'


class Job(models.Model):
    """ Represents a job that is downloading, transforming or updating data as
    part of a Program."""

    program = models.ForeignKey(Program)
    task_id = models.CharField(max_length=128, unique=True)

    def __unicode__(self):
        return self.id


class BatchProgram(Program):
    """A job that runs on some subset of records in a connected system now,
    sometime in the future, or on a recurring schedule."""

    pass


class ListImportProgram(Program):
    csv_file = models.FileField(null=True, default=None)
    # analysis_data = JSONField(default={})

    def analyse(self):
        from program_manager.tasks import analyze_list_import_program
        from qscore.models import QualityScore

        if self.csv_file:
            QualityScore.objects.create(program=self)
            self.status = 'RUN'
            self.save()
            analyze_list_import_program.delay(self)

    def get_absolute_url(self):
        return reverse('import_program_details', kwargs={'pk': self.id})


class TableFilter(models.Model):
    """A table in a connected system.  Tables can be dynamically loaded but
    in initial versions we will hard-code available tables and present these
    table options based on the connected system."""

    batch_program = models.ForeignKey(BatchProgram, null=True, blank=True)
    table_name = models.CharField(max_length=256)  # ex. 'LEAD'


class FieldFilter(models.Model):
    """A field in a connected system and corresponding values that allow the
    user to determine a subset of their records.

    batch_program: the related program
    field: field to filter on from a database table schema
    operator: the appropriate operator based on field type (e.g. >, <, =, older than)
    field_value: a single value or comma-separated values that would make the
        filter true
    """

    program = models.ForeignKey(BatchProgram, null=True, blank=False)
    field = models.ForeignKey(ExternalField)
    operator = models.CharField(max_length=256, default='=', choices=TEXT_OPERATORS+NUM_OPERATORS+DATETIME_OPERATORS+BOOL_OPERATORS)
    field_value = models.CharField(max_length=256, null=True, blank=True)


# class DateFieldFilter(FieldFilter):
#     operator = models.CharField(max_length=256, choices=DATETIME_OPERATORS)
#     value = models.DateField()


class DupMatchRule(models.Model):
    priority = models.IntegerField()
    batch_program = models.ForeignKey(BatchProgram, null=True, blank=True)
    field = models.ForeignKey(ExternalField)
    rule = models.CharField(
        max_length=256,
        choices=MATCH_OPERATORS,
        default='EXACT'
        )

    class Meta:
        ordering = ['priority']


class SurvivingRecordRule(models.Model):
    priority = models.IntegerField()
    batch_program = models.ForeignKey(BatchProgram, null=True, blank=False)
    field = models.ForeignKey(ExternalField)
    rule = models.CharField(
        max_length=256,
        choices=SR_AGE_OPTIONS+SR_NUMBER_OPTIONS+TEXT_OPERATORS,
        default='NEWEST'
        )
    value = models.CharField(max_length=256, null=True, blank=True)

    class Meta:
        ordering = ['priority']


class SurvivingValueRule(models.Model):
    priority = models.IntegerField()
    batch_program = models.ForeignKey(BatchProgram, null=True, blank=False)
    field = models.ForeignKey(ExternalField)
    # field_type = models.CharField(max_length=256)
    rule = models.CharField(
        max_length=256,
        choices=SV_AGE_OPERATORS+SV_NUMBER_OPERATORS+SV_TEXT_OPERATORS+TEXT_OPERATORS,
        default='ADD'
        )
    value = models.CharField(max_length=256, null=True, blank=True)

    class Meta:
        ordering = ['priority']

program_manager/forms.py
from django import forms
from django.utils.html import format_html
from django.forms import ModelChoiceField
from django.utils.encoding import force_text
from django.utils.safestring import mark_safe
from dateutil.parser import parse as dateutil_parse
from django.utils.translation import ugettext_lazy as _

from program_manager import choices
from program_manager.models import (
        BatchProgram, FieldFilter, DupMatchRule, SurvivingRecordRule,
        SurvivingValueRule, ListImportProgram
        )


class BatchProgramNameForm(forms.Form):
    class Meta():
        model = BatchProgram
        fields = ('name')


operator_map = {
        'string': choices.TEXT_OPERATORS + choices.MATCH_OPERATORS,
        'boolean': choices.BOOL_OPERATORS,
        'int': choices.NUM_OPERATORS,
        'double': choices.NUM_OPERATORS,
        'date': choices.DATETIME_OPERATORS,
        'datetime': choices.DATETIME_OPERATORS,
        'binary': choices.TEXT_OPERATORS,
        'id': choices.NUM_OPERATORS,
        'reference': choices.NUM_OPERATORS,
        'currency': choices.NUM_OPERATORS,
        'percent': choices.NUM_OPERATORS,
        'phone': choices.TEXT_OPERATORS,
        'url': choices.TEXT_OPERATORS + choices.MATCH_OPERATORS,
        'email': choices.TEXT_OPERATORS + choices.MATCH_OPERATORS,
        'picklist': choices.TEXT_OPERATORS + choices.MATCH_OPERATORS,
        'multipicklist': choices.TEXT_OPERATORS + choices.MATCH_OPERATORS,
        'location': choices.TEXT_OPERATORS + choices.MATCH_OPERATORS,
        'anyType': choices.TEXT_OPERATORS + choices.NUM_OPERATORS + choices.DATETIME_OPERATORS + choices.BOOL_OPERATORS + choices.MATCH_OPERATORS
}


class OperatorSelect(forms.Select):

    def render_option(self, selected_choices, option_value, option_label):
        if option_value is None:
            option_value = ''
        option_value = force_text(option_value)
        if option_value in selected_choices:
            selected_html = mark_safe(' selected="selected"')
            if not self.allow_multiple_selected:
                selected_choices.remove(option_value)
        else:
            selected_html = ''
        # generate list of css classes from the operator map
        css_classes = []
        for field_type, operators in operator_map.viewitems():
            for op, _ in operators:
                if op == option_value:
                    css_classes.append('opfilter_' + field_type)
        return format_html('<option value="{}" class="{}" {}>{}</option>',
                           option_value,
                           ' '.join(css_classes),
                           selected_html,
                           force_text(option_label))

class FilterForm(forms.ModelForm):

    def __init__(self, program, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.viewitems():
            field.widget.attrs['class'] = 'form-control'
        queryset = program.table_schema.fields.all()
        self.fields['field'].queryset = queryset
        # remove empty option
        self.fields['field'].empty_label = None
        self.fields['field'].widget.choices = self.fields['field'].choices

    def clean(self):
        cleaned_data = super(FilterForm, self).clean()
        field_value = cleaned_data.get('field_value')
        bool_ops, bool_ops_names = zip(*choices.BOOL_OPERATORS)
        num_ops, num_ops_names = zip(*choices.NUM_OPERATORS)
        date_ops, date_ops_names = zip(*choices.DATETIME_OPERATORS)
        op = cleaned_data.get('operator')
        if not field_value and not op in bool_ops:
            self.add_error('field_value', forms.ValidationError(_('This field is required.'), code='required'))
        if field_value:
            if op in num_ops:
                try:
                    float(field_value)
                except ValueError:
                    self.add_error('field_value', forms.ValidationError(_('This operator requires a numeric value.'), code='invalid'))
            elif op in date_ops:
                try:
                     dateutil_parse(field_value)
                except ValueError:
                    self.add_error('field_value', forms.ValidationError(_('This operator requires a datetime value.'), code='invalid'))
        return cleaned_data

    class Meta():
        model = FieldFilter
        fields = ['field', 'operator', 'field_value']
        widgets = {
            'operator': OperatorSelect
        }

class DedupeFormSet(forms.BaseModelFormSet):
    pass

class DedupeRuleForm(forms.ModelForm):

    def __init__(self, program, *args, **kwargs):
        super(DedupeRuleForm, self).__init__(*args, **kwargs)
        self.program = program
        for key, field in self.fields.viewitems():
            current_class = field.widget.attrs.get('class', '')
            new_class = (current_class + ' form-control form-wide').strip()
            if key == 'field':
                new_class += ' selectpicker'
                field.widget.attrs['data-live-search'] = 'true'
            field.widget.attrs['class'] = new_class
        queryset = self.program.table_schema.fields.all()
        self.fields['field'].queryset = queryset
        # remove empty option
        self.fields['field'].empty_label = None
        self.fields['field'].widget.choices = self.fields['field'].choices

    def get_set(self):
        return self.Meta.model.objects.filter(batch_program=self.program)

    def save(self, commit=True):
        instance = super(DedupeRuleForm, self).save(commit=False)
        instance.batch_program = self.program
        #instance.priority = self.get_set().count()
        if commit:
            instance.save()
        return instance

class DupMatchRuleForm(DedupeRuleForm):

    class Meta():
        model = DupMatchRule
        fields = ['field', 'rule']
        labels = {'field': '', 'rule': ''}

class SurvivingRecordRuleForm(DedupeRuleForm):

    class Meta():
        model = SurvivingRecordRule
        fields = ['field', 'rule', 'value']
        labels = {'field': '', 'rule': '', 'value': ''}
        widgets = {
            'rule': forms.Select(attrs={'class': 'rule-operator'}),
            'value': forms.TextInput(attrs={'class': 'rule-value'})
        }

class SurvivingValueRuleForm(DedupeRuleForm):

    class Meta():
        model = SurvivingValueRule
        fields = ['field', 'rule', 'value']
        labels = {'field': '', 'rule': '', 'value': ''}
        widgets = {
            'rule': forms.Select(attrs={'class': 'rule-operator'}),
            'value': forms.TextInput(attrs={'class': 'rule-value'})
        }

class ProgramSettingsForm(forms.ModelForm):

    class Meta():
        model = BatchProgram
        fields = ['dedupe', 'analyze_only']
        labels = {'dedupe': 'Dedupe', 'analyze_only': ''}


class ProgramNameForm(forms.ModelForm):

    class Meta():
        model = BatchProgram
        fields = ['name']
        labels = {'name': ''}


class ListImportProgramForm(forms.ModelForm):
    class Meta:
        model = ListImportProgram
        fields = ('name', 'csv_file')

rl_proto2/templates/program_manager/analysis_confirm.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}


<div class="row">
  <div class="col-md-5 col-md-offset-1">
      <h3 class="subtle_header">New analysis program</h3>
  </div>
  <!--<div class="col-md-5" align="right" >
      <div class="btn-group btn-lg" role="group">
        <a href="{% url 'analysis_select' %}" class="btn btn-lg btn-default ">1</a>
        <a href="{% url 'analysis_confirm' %}" class="btn btn-lg btn-default active">2</a>
      </div>
  </div>-->
</div>
<br>
<div class="row">
    <div class="col-md-8 col-md-offset-2 well">
        <!-- nested rows & columns -->
        <div class="row">
            <div class="col-md-12" align="center">
                <h3>Begin Analysis Program?</h3>
                <p>Ready to begin your data analysis?</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2" align="center">
                <a href="#" class="btn btn-lg btn-default" style="margin:20px">No, cancel analysis
                <a href="#" class="btn btn-lg btn-success" style="margin:20px">Yes, begin analysis</a>
            </div>
        </div>
        <!-- / nested rows & columns -->
    </div>
</div>
<br>


{% endblock %}

rl_proto2/templates/program_manager/batch_select.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block layout %}
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h3>Step 1: Select a Data Set</h3>
  </div>
  <div class="col-md-5" align="right" >
      {% include 'includes/batch_program_button_group.html' %}
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-offset-1 col-md-offset-10">
    <div class="row">
      <div class="col-md-3">
        <h5>Select a Database</h5>
        <br>
        <div class="form-group">
          <select class="form-control" disabled>
            <option selected value="salesforce" >Salesforce</option>
            <option value="marketo">Marketo</option>
            <option value="custom_db">ERP System</option>
          </select>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1">
        <h5>Select a Table</h5>
        <!-- For each available table... -->
            <div class="row">
                <div class="col-sm-6">
                    <div class="checkbox">
                      <label><input type="checkbox" value="" checked disabled>Leads</label>
                    </div>
                    <div class="checkbox">
                      <label><input type="checkbox" value="" disabled>Contacts</label>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="checkbox disabled">
                      <label><input type="checkbox" value="" disabled>Accounts</label>
                    </div>
                    <div class="checkbox">
                      <label><input type="checkbox" value="" disabled>Opportunities</label>
                    </div>
                </div>
            </div>
      </div>
      <div class="col-md-3 col-md-offset-1" style="height:250px">
        <h5>Add Filters</h5>
        <br>
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            {% if not field_filters %}
            <p>No filters selected</p>
            {% else %}
                {% for i in field_filters %}
                    <span style="font-size:16px" class="label label-primary">
                      <i>{{ i.field.get_label }}</i>
                      {{ i.get_operator_display }}
                      {{ i.field_value }}  &nbsp;&nbsp;&nbsp;
                      <form action="{% url 'delete_fieldfilter' i.pk %}" method="POST" style="display: inline-block;">
                        {% csrf_token %}
                        <button class="btn-link btn-link-delete-label" type="submit">
                          <i class="fa fa-times-circle fa-inverse"></i>
                        </button>
                      </form>
                    </span>
                    <br>
                    <br>
                {% endfor %}
            {% endif %}
          </div>
        </div>
        <div class="row" align="center">
          <a href="#" data-toggle="modal" data-target="#FiltersModal" class="btn btn-sm btn-default">Add a Filter</a>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12" align="center">
    <a href="{% url 'programs' %}" class="btn btn-lg btn-default">Cancel</a>
    <a href="{% url 'select_actions' program.pk %}" class="btn btn-lg btn-success">Continue</a>
  </div>
</div>

<!-- Filters Modal -->
<div class="modal fade" id="FiltersModal" tabindex="-1" role="dialog" aria-labelledby="FiltersModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="FiltersModalLabel">Add a Filter</h4>
      </div>

      <form method="POST" action="{% url 'batch_select' program.pk %}">
        {% csrf_token %}
        <div class="modal-body">
          <table class="table well">
            {{ form.non_field_errors }}
            <thead>
              <tr>
                <td>Field Name</td>
                <td>Operator</td>
                <td class="value-column">Value</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  {{ form.field | set_data:"live-search:true" | add_class:"selectpicker" }}
                </td>
                <td>
                  {{ form.operator }}
                </td>
                <td class="value-column">
                  {{ form.field_value }}
                </td>
              </tr>
              <tr>
                <td>
                  {% if form.field.errors %}
                  <div class="alert alert-danger">
                    {{ form.field.errors.as_text }}
                  </div>
                  {% endif %}
                </td>
                <td>
                  {% if form.operator.errors %}
                  <div class="alert alert-danger">
                    {{ form.operator.errors.as_text }}
                  </div>
                  {% endif %}
                </td>
                <td>
                  {% if form.field_value.errors %}
                  <div class="alert alert-danger">
                    {{ form.field_value.errors.as_text }}
                  </div>
                  {% endif %}
                </td>
              </tr>
            </tbody>
          </table>

          <div class="modal-footer">
            <button type="submit" class="btn btn-success">Add this filter</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script type='text/javascript'>
    var type_table = {{ type_table }};
    $(document).ready(function () {
      /* open modal if there are any errors in the form */
      {% if form.errors %}
      $('#FiltersModal').modal('show');
      {% endif %}
      /* filter operators depending on the selected field type */
      var allOptions = $('#id_operator option')
        $('#id_field').change(function () {
          $('#id_operator option').remove();
          var type = type_table[$('#id_field option:selected').text()]
          var value_cell  = $(".value-column");
          if (type == "boolean") {
            value_cell.hide();
          } else {
            value_cell.show();
          }
          var opts = allOptions.filter('.opfilter_' + type);
          $.each(opts, function (i, j) {
            $(j).appendTo('#id_operator');
          });

        }).change();
    });
</script>

{% endblock %}

rl_proto2/templates/program_manager/dashboard.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}
<div class="row" align="center">
  {% include 'includes/messages.html' %}
</div>

{% if programs %}

    {% include 'includes/program_header.html' %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <!-- Display 3x3 rows of dashboard elements -->
            <div class="row">
            {% for item in programs %}
                <div class="col-md-4 col-sm-4 well program-item">
                    <div class="row" align="center">
                        <div class="col-md-12">
                            <span style="font-size:24px">{{ item.name | truncatechars:20 }}</span><br>
                            <!-- Display Status in appropriately colored label with
                            optional icon -->
                            <span style="font-size:16px"
                                {% if item.status == 'RUN' %}
                                  class="label label-primary"><i class="fa fa-cog fa-spin"></i>
                                {% elif item.status == 'PEND' %}
                                  class="label label-primary"><i class="fa fa-circle-o-notch fa-spin"></i>
                                {% elif item.status == 'PAUSE' %}
                                  class="label label-default"><i class="fa fa-pause"></i>
                                {% elif item.status == 'ERROR' %}
                                  class="label label-danger"><i class="fa fa-exclamation-triangle"></i>
                                {% elif item.status == 'COMPL' %}
                                  class="label label-success"><i class="fa fa-check"></i>
                                {% endif %}

                            {{ item.get_status_display }}</span>
                            <!-- / display status -->
                        </div>
                    </div>
                    <div class="row" style="height:150px">
                        <div align="center">
                        {% with item.get_current_quality_score as qscore %}
                            {% if qscore.score > 0 %}
                                <!-- Gauge via JustGage -->
                                <div id="gauge_{{ item.id }}"></div>
                                <script>
                                  var g = new JustGage({
                                    id: "gauge_{{ item.id }}",
                                    value: {{ item.get_current_quality_score.score }},
                                    min: 0,
                                    max: 100,
                                    // label: "Excellent Quality",
                                    levelColors : [  "#FF3300", "#FF9900", "#FFFF00",  "#33CC33" ],
                                    // title: "Customer Contacts"
                                  });
                                </script>
                                <!-- End Gauge -->
                            {% else %}
                                <br>
                                <p>Calculating Quality Score...</p>
                                <i class="fa fa-circle-o-notch fa-spin fa-5x"></i>
                            {% endif %}
                        {% endwith %}
                        </div>
                    </div>
                    <div class="row" align="center">
                          <!-- Single button -->
                          <div class="btn-group dropup">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Options <span class="caret"></span>
                            </button>
                            <!-- inherit dropdown menu shared with other templates -->
                            {% include 'includes/program_btn_options.html' %}
                          </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>

            <div class="row">
                {% endif %}
                {% if forloop.last %}
            </div>
                {% endif %}
            {% endfor %}
            <!-- End dashboard row generator -->
        </div>
    </div>



{% else %}
<br>
<br>
<br>
<br>
<br>
<div class="row">
  <div class="col-md-12" align="center">
    <h5>It looks like you haven't created any programs yet {{ user.first_name }}.  Let's fix that!<h5>
    <a href="{% url 'select_program_type' %}" class="btn btn-lg btn-success">Create your first program</a>
  </div>
</div>

{% endif %}

<script>
    $(function () {
        $('.archive-program').click(function () {
            var $this = $(this), url = $this.data('url'), $container = $this.parents('.program-item');
            $container.append($('<div class="loading-container"><i class="fa fa-spinner fa-pulse"></i></div>'));
            $.get(url, function (){
                $container.remove();
            });
        });
    });
</script>
{% endblock %}

rl_proto2/templates/program_manager/deduperule_list.html
{% for element in elements %}
<tr>
  <td style="width: 35%">{{ element.field.get_label }}</td>
  <td style="width: 60%">{{ element.get_rule_display }}</td>
  <td style="vertical-align: middle;">
    <form class="delete-form" method="POST" action={% url 'delete_dupmatchrule' element.pk %}>
      {% csrf_token %}
      <button type="submit">
        <i class="fa fa-close text-default"></i>
      </button>
    </form>
  </td>
</tr>
{% endfor %}

rl_proto2/templates/program_manager/no_oauth.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}
<br>
<br>
<br>
<br>
<br>
<div class="row">
  <div class="col-md-12" align="center">
    <h5>It looks like you haven't added a connection to a data source yet, {{ user.first_name }}.
      Let's fix that!<h5>
    <a href="{% url 'accounts:settings' %}" class="btn btn-lg btn-warning">Add a connection</a>
  </div>
</div>
{% endblock %}